version: "2"

services:
  trolley:
    image: pittvax/trolley:latest
    container_name: "Trolley"
    working_dir: /root/trolley
#    environment:
    volumes:
      - ./:/root/trolley
#    entrypoint: sh
#    command: -c "tail -f /dev/null"