version: '3'
services:
  jython:
    image: harisekhon/jython
    volumes:
    - /taoi:/home


    docker run -it --mount type=bind,src=c:\users\jraviotta\documents\repos\trolley\taoi,dst=/taoi --rm  harisekhon/jython
    docker run -it --rm -v ${PWD}:/scratch mcandre/docker-jython:latest jython